# Generated by Django 4.1.3 on 2022-11-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('ram', models.IntegerField()),
                ('storagge', models.IntegerField()),
                ('condition', models.CharField(choices=[('refurbished', 'refurbished'), ('new', 'new')], max_length=120)),
                ('descriptions', models.TextField()),
                ('image', models.ImageField(upload_to='images/laptops/')),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('position', models.CharField(choices=[('founder', 'founder'), ('sponsor', 'sponsor'), ('ict', 'ict')], max_length=120)),
                ('person_image', models.ImageField(upload_to='images/person/')),
            ],
        ),
    ]
